// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrsQuotes.Api.Database;

#nullable disable

namespace MrsQuotes.Api.Migrations
{
    [DbContext(typeof(MrsQuotesDbContext))]
    [Migration("20260723191842_AddQuoteItemLocations")]
    partial class AddQuoteItemLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppointmentEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AppointmentStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssessorId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RequestDetails")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("SiteAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("AssessorId", "Status", "AppointmentStart");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.PriceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AutomaticFeeCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ItemCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("MarkupPercentage")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("PricingMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PricingNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("QuoteGroup")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ScheduleVersion")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("SourceSheet")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("SystemGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("TradeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TradeGroup")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .IsUnique()
                        .HasFilter("[ItemCode] IS NOT NULL");

                    b.HasIndex("Active", "ScheduleVersion", "TradeCode");

                    b.ToTable("PriceItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Category = "Emergency Work",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Initial site inspection and quick make-safe allowance",
                            ItemCode = "MRS-001",
                            PricingMode = "fixed",
                            QuoteGroup = "Emergency",
                            Rate = 850m,
                            ScheduleVersion = 0,
                            Section = "Starter",
                            SortOrder = 0,
                            SourceSheet = "Starter",
                            SystemGenerated = false,
                            TradeCode = "",
                            TradeGroup = "",
                            TradeName = "",
                            Unit = "Each"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Category = "Building Work",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Replace damaged ceiling board",
                            ItemCode = "MRS-002",
                            PricingMode = "fixed",
                            QuoteGroup = "Building",
                            Rate = 420m,
                            ScheduleVersion = 0,
                            Section = "Starter",
                            SortOrder = 0,
                            SourceSheet = "Starter",
                            SystemGenerated = false,
                            TradeCode = "",
                            TradeGroup = "",
                            TradeName = "",
                            Unit = "m2"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Category = "Painting",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Prepare and paint interior wall",
                            ItemCode = "MRS-003",
                            PricingMode = "fixed",
                            QuoteGroup = "Building",
                            Rate = 95m,
                            ScheduleVersion = 0,
                            Section = "Starter",
                            SortOrder = 0,
                            SourceSheet = "Starter",
                            SystemGenerated = false,
                            TradeCode = "",
                            TradeGroup = "",
                            TradeName = "",
                            Unit = "m2"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Category = "Waterproofing",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Torch-on waterproofing repair",
                            ItemCode = "MRS-004",
                            PricingMode = "fixed",
                            QuoteGroup = "Roofing",
                            Rate = 310m,
                            ScheduleVersion = 0,
                            Section = "Starter",
                            SortOrder = 0,
                            SourceSheet = "Starter",
                            SystemGenerated = false,
                            TradeCode = "",
                            TradeGroup = "",
                            TradeName = "",
                            Unit = "m2"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Category = "Cleaning",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Post-repair cleaning crew",
                            ItemCode = "MRS-005",
                            PricingMode = "fixed",
                            QuoteGroup = "Building",
                            Rate = 280m,
                            ScheduleVersion = 0,
                            Section = "Starter",
                            SortOrder = 0,
                            SourceSheet = "Starter",
                            SystemGenerated = false,
                            TradeCode = "",
                            TradeGroup = "",
                            TradeName = "",
                            Unit = "Hour"
                        });
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("ArchivedPhotoCount")
                        .HasColumnType("int");

                    b.Property<int>("AssessorId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ErpQuoteNumber")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhotoArchiveUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("PhotoPurgeEligibleAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PhotosPurgedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("QuoteAdministratorId")
                        .HasColumnType("int");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("RequestDetails")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("SiteAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasFilter("[AppointmentId] IS NOT NULL");

                    b.HasIndex("AssessorId");

                    b.HasIndex("ClientId");

                    b.HasIndex("QuoteAdministratorId");

                    b.HasIndex("QuoteNumber")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.QuoteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("InputAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PriceItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("QuoteId")
                        .HasColumnType("int");

                    b.Property<bool>("SystemGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("TradeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("UnitRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PriceItemId");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteItems");
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.QuotePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("QuoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuotePhotos");
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("QuoteAdministratorId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("QuoteAdministratorId");

                    b.HasIndex("Role");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.Appointment", b =>
                {
                    b.HasOne("MrsQuotes.Api.Database.Models.User", "Assessor")
                        .WithMany("Appointments")
                        .HasForeignKey("AssessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MrsQuotes.Api.Database.Models.Client", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessor");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.Quote", b =>
                {
                    b.HasOne("MrsQuotes.Api.Database.Models.Appointment", "Appointment")
                        .WithOne("Quote")
                        .HasForeignKey("MrsQuotes.Api.Database.Models.Quote", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MrsQuotes.Api.Database.Models.User", "Assessor")
                        .WithMany("Quotes")
                        .HasForeignKey("AssessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MrsQuotes.Api.Database.Models.Client", "Client")
                        .WithMany("Quotes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MrsQuotes.Api.Database.Models.User", "QuoteAdministrator")
                        .WithMany()
                        .HasForeignKey("QuoteAdministratorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Appointment");

                    b.Navigation("Assessor");

                    b.Navigation("Client");

                    b.Navigation("QuoteAdministrator");
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.QuoteItem", b =>
                {
                    b.HasOne("MrsQuotes.Api.Database.Models.PriceItem", "PriceItem")
                        .WithMany("QuoteItems")
                        .HasForeignKey("PriceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MrsQuotes.Api.Database.Models.Quote", "Quote")
                        .WithMany("Items")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceItem");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.QuotePhoto", b =>
                {
                    b.HasOne("MrsQuotes.Api.Database.Models.Quote", "Quote")
                        .WithMany("Photos")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.User", b =>
                {
                    b.HasOne("MrsQuotes.Api.Database.Models.User", "QuoteAdministrator")
                        .WithMany("AssignedAssessors")
                        .HasForeignKey("QuoteAdministratorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("QuoteAdministrator");
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.Appointment", b =>
                {
                    b.Navigation("Quote");
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.Client", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.PriceItem", b =>
                {
                    b.Navigation("QuoteItems");
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.Quote", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("MrsQuotes.Api.Database.Models.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AssignedAssessors");

                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
